services:
  cocodo-wawi:
    build: .
    container_name: cocodo-wawi
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cocodo.rule=Host(`cocodo.worknetic.de`)"
      - "traefik.http.routers.cocodo.entrypoints=websecure"
      - "traefik.http.routers.cocodo.tls=true"
      - "traefik.http.routers.cocodo.tls.certresolver=mytlschallenge"
      - "traefik.http.services.cocodo.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
